version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - ../.env.example
    depends_on:
      - pg
      - redis
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
  pg:
    image: postgres:15
    environment:
      POSTGRES_USER: nianbao
      POSTGRES_PASSWORD: nianbao
      POSTGRES_DB: nianbao
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
